name: Automation Silent

on:
  push:
  schedule:
    - cron: "0 17 * * *"  # UTC+8 01:00  UTC+0 17:00
  workflow_dispatch:

jobs:
  setup_config:
    uses: kevin77688/GithubActionTest/.github/workflows/Config_Setup_Template.yml@main
    with:
      notify: false
      fastReport: false
    secrets: inherit

  automation:
    needs: setup_config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache config files
        id: config-cache
        uses: actions/cache@v3
        with:
          path: config.yml
          key: ${{ hashFiles('**/Config_Setup_Template.yml') }}-ver_1.0

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Setup playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install

      - name: Bahamut Automation
        run: |
          npx playwright install chrome
          npx bahamut-automation -c config.yml
      - name: Keep Alive
        uses: gautamkrishnar/keepalive-workflow@master