name: Automation Docker

on:
  # push:
  schedule:
    - cron: "0 9 * * *" # UTC+8 17:00  UTC+0 09:00
  workflow_dispatch:

jobs:
  setup_config:
    uses: kevin77688/GithubActionTest/.github/workflows/Config_Setup_Template.yml@main
    with:
      notify: false
      fastReport: false
    secrets: inherit

  automation:
    needs: setup_config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache config files
        uses: actions/cache@v3
        with:
          path: config.yml
          key: ${{ hashFiles('**/Config_Setup_Template.yml') }}-ver_1.0
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          docker run --rm -v "$(pwd)/config.yml:/config.yml" jacoblincool/bahamut-automation:v1.0.0-pre.7

      - name: Keep Alive
        uses: gautamkrishnar/keepalive-workflow@master
