name: Automation Silent

on:
  push:
  schedule:
    - cron: "0 17 * * *"  # UTC+8 01:00  UTC+0 17:00
  workflow_dispatch:

jobs:
  setup_config:
    container:
      image: mcr.microsoft.com/playwright:v1.24.0-focal
      uses: kevin77688/GithubActionTest/.github/workflows/Config_Setup_Template.yml@main
      with:
        notify: false
        fastReport: false
      secrets: inherit

  automation:
    needs: setup_config
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.24.0-focal
    steps:
      - uses: actions/checkout@v3
      - name: Cache config files
        id: config-cache
        uses: actions/cache@v3
        with:
          path: config.yml
          key: ${{ hashFiles('**/Config_Setup_Template.yml') }}-ver_1.0

      - name: Install dependencies
        run: |
          apt-get update > /dev/null
          apt-get -y install build-essential > /dev/null
          npm install
          npx playwright install

      - name: Bahamut Automation
        run: npx bahamut-automation -c config.yml

      - name: Keep Alive
        uses: gautamkrishnar/keepalive-workflow@master