name: Setup Config Files

on:
  workflow_call:
    inputs:
      notify:
        required: false
        default: false
      fastReport:
        required: false
        default: false


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache config files
        id: config-cache
        uses: actions/cache@v3
        with:
          path: ~/config.yml
          key: ${{ hashFiles('**/config.yml') }}-ver_a_1

      - name: Setup config files
        if: steps.config-cache.outputs.cache-hit != 'true'
        run: |
          sed -i "s|$username|\"${{secrets.USERNAME}}\"|g" config.yml
          sed -i "s|$password|\"${{secrets.PASSWORD}}\"|g" config.yml
          sed -i "s|$line_token|\"${{secrets.LINE_TOKEN}}\"|g" config.yml
          sed -i "s|$discord_webhook_url|\"${{secrets.DISCORD_WEBHOOK_URL}}\"|g" config.yml
          
          if [ $notify != true ]; then
            sed -i 's/line_notify/# line_notify/g' config.yml
            sed -i 's/token/# token/g' config.yml
          fi

          if [ $fastReport == true ]; then
            sed -i 's/guild/# guild/g' config.yml
            sed -i 's/answer/# answer/g' config.yml
            sed -i 's/lottery/# lottery/g' config.yml
            sed -i 's/max_attempts/# max_attempts/g' config.yml
          fi



      

